#cloud-config
# 
runcmd:
 - [ yum ,install, -y , httpd ]
 - [ yum ,install, -y , wget ]
 - [ /bin/systemctl, enable, httpd ]
 - [ /bin/systemctl, start, httpd]
 - [ /bin/systemctl, status, httpd]
 - [ wget, "https://raw.githubusercontent.com/mrbbowden/jchome/main/index.html",-O,/var/www/html/index.html ]
 - [ yum,update ,-y ]
 - [ reboot]

#package_upgrade: true
#power_state:
#  mode: reboot
#  message: Bye Bye
#  timeout: 30
#  condition: True