#cloud-config
# 
packages:
  - httpd

package_upgrade: true
runcmd:
 - [ /bin/systemctl, enable, httpd ]
 - [ /bin/systemctl, start, httpd]
 - [ /bin/systemctl, status, httpd]

#
write_files:
  - path: /var/www/html/index.html
    content: |
         <html>
         Welcome
         </html>
#power_state:
#  mode: reboot
#  message: Bye Bye
#  timeout: 30
#  condition: True